export TERM="xterm-256color"
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="powerlevel10k/powerlevel10k"
source $ZSH/oh-my-zsh.sh

HISTCONTROL=ignoreboth
HISTSIZE=5000
HISTFILESIZE=10000

setopt APPEND_HISTORY
setopt share_history

## Completions
eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)

export KUBECONFIG=~/.kube/config
export GOPATH=/usr/local/go/bin
export PROMPT_COMMAND="history -a; history -n"
export KUBE_EDITOR=vim
# export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-11.0.9.11-4.fc33.x86_64"
export PATH="$JAVA_HOME/bin:$GOPATH:$PATH"

source <(stern --completion=zsh)
source <(gh completion -s zsh)

alias k=kubectl
alias kx=kubectx
alias ks=kubens
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
alias vi=vim

bindkey "\033[1~" beginning-of-line
bindkey "\033[4~" end-of-line
bindkey "^[[1;3C" forward-word
bindkey "^[[1;3D" backward-word
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
source ~/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
